routes/web.php
<?php
use App\Http\Controllers\PerteneceController;
use App\Http\Controllers\PracticaController;
use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\CursoController;
use App\Http\Controllers\PresentaController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
})->name('inicio');
// enrutamiento para controlador alumno
Route::resource('alumno', AlumnoController::class);

// entutamiento para controlador curso
Route::resource('curso', CursoController::class);
// enrutamiento para controlador practica
Route::resource('practica', PracticaController::class);
// enrutamiento para controlador presenta
Route::resource('presenta', PresentaController::class);
// enrutamiento para perteneces
Route::resource('pertenece', PerteneceController::class);

// enrutamiento adicional para practicas
Route::controller(PracticaController::class)->group(function () {
    Route::get('/practica/confirmar/{practica}',
     'confirmar')->name('practica.confirmar');
});
// enrutamiento adicional para cursos
Route::controller(CursoController::class)->group(function () {
    Route::get('/curso/confirmar/{curso}',
     'confirmar')->name('curso.confirmar');
});

// entrutamiento adicional para alumnos
Route::controller(AlumnoController::class)->group(function () {
    Route::get('/alumno/confirmar/{alumno}',
     'confirmar')->name('alumno.confirmar');

});
// entrutamiento adicional para pertenece
Route::controller(PerteneceController::class)->group(function () {
    Route::get('/pertenece/confirmar/{pertenece}',
     'confirmar')->name('pertenece.confirmar');
});

app/Models/Presenta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\Schema;

class Presenta extends Model
{

    use HasFactory;
    //nombre de la tabla
    protected $table = 'presentas';
    // campos de la tabla
    protected $fillable =
    ['alumno_id', 'practica_id','nota'];

    // creamos un atributo estatico con los labels
    public static $labels = [
        'id' => 'Id',
        'alumno_id' => 'Alumno Id',
        'practica_id' => 'Practica Id',
        'nota' => 'Nota',
    ];

    // metodo para devolver el label de un campo
    public function getAttributeLabel($key)
    {
        return self::$labels[$key] ?? $key;
    }

    public function getFields()
    {
        return Schema::getColumnListing($this->table());
    }
    // vamos a crear las relacciones
    // relacion uno a muchos con cursos
    public function alumno() :BelongsTo
    {
        return $this->belongsTo(Alumno::class);
    }
    public function practica():BelongsTo
    {
        return $this->belongsTo(Pertenece::class);
    }
}

app/Http/Controllers/PresentaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Presenta;
use Illuminate\Http\Request;
use App\Models\Alumno;
use App\Models\Practica;

class PresentaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $presentas=Presenta::all();
        return view('presenta.index',compact('presentas'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $alumnos=Alumno::all();
        $practicas=Practica::all();
        return view ('presenta.create', compact( 'alumnos','practicas'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Presenta $request)
    {
        //
        $presenta=Presenta::create($request->all());
        return redirect()
        ->route('presenta.show', $presenta);
        // ->with('mensaje', 'Presenta creada');
    }

    /**
     * Display the specified resource.
     */
    public function show(Presenta $presentum)
    {
        //
        return view('presenta.show',compact('presenta'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Presenta $resenta )
    {
        //
        $alumnos=Alumno::all();
        $practicas=Practica::all();
        return view('presenta.edit',compact('presenta','alumnos','practicas'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update( Request $request, Presenta $presenta)
    {
        $presenta->update($request->all());
        return redirect()
        ->route('presenta.show', $presenta);
       // ->with('mensaje', 'Presenta actualizada');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Presenta $presentum)
    {
        //
        $presentum->delete();
        return redirect()
        ->route('presenta.index');
        // ->with('mensaje', 'Presenta eliminada');
    }
    public function confirmar(Presenta $presenta)   
    {
        return view('presenta.confirmar',compact('presenta'));
    }
}

resources/views/presenta/create.blade.php
@extends('layouts.main')

@section('content')
<div class="tarjeta">
    <form action="{{ route('presenta.store') }}" method="post" enctype="multipart/form-data">
        @csrf

        <div>
            <label for="alumno.id">Alumno Id</label>
            <select name="alumno.id">
                @foreach ($alumnos as $alumno)
                    <option value="{{ $alumno->id }}">{{ $alumno->nombre }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label for="practica.id">Practica Id</label>
            <select name="practica.id">
                @foreach ($practicas as $practica)
                    <option value="{{ $practica->id }}">{{ $practica->titulo }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label for="nota">Nota</label>
            <input type="number" name="nota" id="nota">
        </div>

        <div>
            <button type="submit">Enviar</button>
        </div>
    </form>
    </div>
@endsection

resources/views/presenta/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="tarjeta">
        <form action="{{ route('presenta.update', $presenta) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')


            <div>
                <label>Alumno Id</label>
                <select name="alumno.id">
                    @foreach ($alumnos as $alumno)
                        <option value="{{ $alumno->id }}" {{ $presenta->alumno_id == $alumno->id ? 'selected' : '' }}>
                            {{ $alumno->nombre }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label>Id Practica</label>
                <select name="practica.id">
                    @foreach ($practicas as $practica)
                        <option value="{{ $practica->id }}" {{ $presenta->practica_id == $practica->id ? 'selected' : '' }}>
                            {{ $practica->titulo }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label>Nota</label>
                <input type="number" name="nota" value="{{ $presenta->nota }} required">

                <div>
                    <button type="submit">Enviar</button>
                </div>

        </form>
    </div>
@endsection

resources/views/presenta/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="listado">
        @foreach ($presentas as $presenta)
            <div class="tarjeta">
                <ul>
                    <li>Id:{{ $presenta->id }}</li>
                    <li>Alumno Id:{{ $presenta->alumno_id }}</li>
                    <li>Practica Id:{{ $presenta->practica_id }}</li>
                    <li>Nota:{{ $presenta->nota }}</li>
                </ul>
                <div class="botones">
                    <a href="{{ route('presenta.show', $presenta) }}" class="boton">Ver</a>
                    <a href="{{ route('presenta.edit', $presenta) }}" class="boton">Actualizar</a>
                    <form action="{{ route('presenta.destroy', $presenta) }}" method="post" iliminar class="form-inline">
                        @csrf
                        @method('delete')
                        <button type="submit">Eliminar</button>
                    </form>
                    
                </div>

            </div>
        @endforeach
    </div>
@endsection

resources/views/presenta/show.blade.php
@extends('layouts.main')

@section('content')
<div class="listado">
<ul>
    <li>Id:{{ $presenta->id }}</li>
    <li>Alumno Id:{{ $presenta->alumno->id }}</li>
    <li>Practica Id:{{ $presenta->practica->id }}</li>
    <li>Nota:{{ $presenta->nota }}</li>
</ul>
    <div class="botones">
        <a href={{ route('presenta.show', $presenta) }} class="boton">Ver</a>
        <a href={{ route('presenta.edit', $presenta)}} class="boton">Actualizar</a>
        <form action="{{ route('presenta.destroy', $presenta) }}" method="post" id="eliminar" class="form-inline">
            @csrf
            @method('delete')
            <button type="submit">Eliminar</button>
        </form>
        <a href="{{ route('presenta.confirmar', $presenta) }}" class="boton">Eliminar de otra forma</a>
    </div>
</div>
@endsection