routes/web.php
<?php
use App\Http\Controllers\PerteneceController;
use App\Http\Controllers\PracticaController;
use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\CursoController;
use App\Http\Controllers\PresentaController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
})->name('inicio');
// enrutamiento para controlador alumno
Route::resource('alumno', AlumnoController::class);

// entutamiento para controlador curso
Route::resource('curso', CursoController::class);
// enrutamiento para controlador practica
Route::resource('practica', PracticaController::class);
// enrutamiento para controlador presenta
Route::resource('presenta', PresentaController::class);
// enrutamiento para perteneces
Route::resource('pertenece', PerteneceController::class);

// enrutamiento adicional para practicas
Route::controller(PracticaController::class)->group(function () {
    Route::get('/practica/confirmar/{practica}',
     'confirmar')->name('practica.confirmar');
});
// enrutamiento adicional para cursos
Route::controller(CursoController::class)->group(function () {
    Route::get('/curso/confirmar/{curso}',
     'confirmar')->name('curso.confirmar');
});

// entrutamiento adicional para alumnos
Route::controller(AlumnoController::class)->group(function () {
    Route::get('/alumno/confirmar/{alumno}',
     'confirmar')->name('alumno.confirmar');

});
// entrutamiento adicional para pertenece
Route::controller(PerteneceController::class)->group(function () {
    Route::get('/pertenece/confirmar/{pertenece}',
     'confirmar')->name('pertenece.confirmar');
});

app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Schema;


class Curso extends Model
{

    use HasFactory;
    //nombre de la tabla
    protected $table = 'cursos';
    // campos de la tabla
    protected $fillable =
    ['nombre', 'duracion','fechacomienzo','observaciones'];

    // creamos un atributo estatico con los labels
    public static $labels = [
        'id' => 'Id',
        'nombre' => 'Nombre',
        'duracion' => 'Duración',
        'fechacomienzo' => 'Fecha de Comienzo',
        'observaciones' => 'Observaciones',
    ];

    // metodo para devolver el label de un campo
    public function getAttributeLabel($key)
    {
        return self::$labels[$key] ?? $key;
    }

    public function getFields()
    {
        return Schema::getColumnListing($this->table());
    }
    // vamos a crear las relacciones
    // relacion uno a muchos con cursos
    public function practicas() :HasMany
    {
        return $this->hasMany(Practica::class);
    }
    public function perteneces():HasMany
    {
        return $this->hasMany(Pertenece::class);
    }
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Curso;
use Illuminate\Http\Request;

class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //  $cursos=Curso::paginate(3);
        $cursos=Curso::all();
        return view('curso.index',compact('cursos'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('curso.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // $request->validate([
        //     'nombre' => 'required',
        //     'duracion' => 'required',
        // ], [
        //     'required' => 'El campo :attribute es obligatorio',
        // ]);
        $curso=Curso::create($request->all());
        return redirect()
        ->route('curso.show', $curso)
        ->with('mensaje', 'Curso creado');
        
        
    }

    /**
     * Display the specified resource.
     */
    public function show(Curso $curso)
    {
        return view('curso.show',compact('curso'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Curso $curso)
    {
        return view('curso.edit',compact('curso'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Curso $curso)
    {
        $request->validate([
            'nombre' => 'required',
            'duracion' => 'required',
        ], [
            'required' => 'El campo :attribute es obligatorio',
        ]);
        $curso->update($request->all());
        return redirect()
        ->route('curso.show', $curso)
        ->with('mensaje', 'Curso actualizado');
       
        
        
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Curso $curso)
    {
        $curso->delete();
        return redirect()
        ->route('curso.index')
        ->with('mensaje', 'Curso eliminado');
    }
    public function confirmar(Curso $curso){
        return view('curso.confirmar',compact('curso'));
    }
}

resources/views/curso/confirmar.blade.php
@extends('layouts.main')

@section('content')
    <h1>Eliminando registro</h1>
    <div>
        ¿Estas seguro de que quieres borrar el registro?
    </div>
    <div class="tarjeta">
        <ul>
            <li>id:{{ $curso->id }}</li>
            <li>Nombre:{{ $curso->nombre }}</li>
            <li>Duracion:{{ $curso -> duracion }}</li>
            <li>Fecha de Comienzo:{{ $curso->fechacomienzo }}</li>
            <li>Observaciones:{{ $curso->observaciones }}</li>
        </ul>
        <form action="{{ route('curso.destroy', $curso) }}" method="post" class="form-inline">
            @csrf
            @method('delete')
            <button type="submit" class="boton">Borrar</button>
        </form>
    </div>
@endsection

resources/views/curso/create.blade.php
@extends('layouts.main')

@section('content')
<div class="tarjeta">
<form action="{{ route('curso.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre">
    </div>
    <div>
        <label for="duracion">Duración</label>
        <input type="number" name="duracion" id="duracion">
    </div>
    <div>
        <label for="fechacomienzo">Fecha de Comienzo</label>
        <input type="date" name="fechacomienzo" id="fechacomienzo">
    </div>
    <div>
        <label for="observaciones">Observaciones</label>
        <input type="text" name="observaciones" id="observaciones">
    </div>
   
    <div>
        <button type="submit" class="boton">Enviar</button>
    </div>
</form>

</div>
@endsection

resources/views/curso/edit.blade.php
@extends('layouts.main')

@section('content')
<div class="tarjeta">
    <form action="{{ route('curso.update', $curso) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div>
            <label>Id</label>
            <input type="number" name="id" required value="{{ $curso->id }} ">
        </div>
        <div>
            <label>Nombre</label>
            <input type="text" name="nombre" required value="{{ $curso->nombre }} ">
        </div>
        <div>
            <label>Duración</label>
            <input type="number" name="duracion" value="{{ $curso->duracion }}  required">
        </div>
        <div>
            <label>Fecha Comienzo</label>
            <input type="date" name="fechacomienzo" value="{{ $curso->fechacomienzo }} required">
        </div>
        <div>
            <label>Observaciones</label>
            <input type="text" name="observaciones" value="{{ $curso->observaciones }} required">
        </div>
        <div>
            <button type="submit" class="boton">Enviar</button>
        </div>

    </form>

</div>  
@endsection

resources/views/curso/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="listado">
        @foreach ($cursos as $curso)
            <div class="tarjeta">
                <ul>
                    <li>Id:{{ $curso->id }}</li>
                    <li>Nombre:{{ $curso->nombre }}</li>
                    <li>Duracion:{{ $curso->duracion }}</li>
                    <li>Fecha de Comienzo:{{ $curso->fechacomienzo }}</li>
                    <li>Observaciones:{{ $curso->observaciones }}</li>

                </ul>
                <div class="botones">
                    <a href="{{ route('curso.show', $curso) }}" class="boton">Ver</a>
                    <a href="{{ route('curso.edit', $curso) }}" class="boton">Actualizar</a>
                    <form action="{{ route('curso.destroy', $curso) }}" method="post" id="eliminar" class="form-inline">
                        @csrf
                        @method('delete')
                        <button type="submit" class="boton">Eliminar</button>
                    </form>
                    <a href="{{ route('curso.confirmar', $curso) }}" class="boton">Eliminar de otra forma</a>
                </div>

            </div>
        @endforeach

    </div>
@endsection

resources/views/curso/show.blade.php
@extends('layouts.main')

@section('content')
    <div clas="listado">
    
                  
            
        
        <div class="tarjeta">
        <ul>
          
            <li>Id:{{ $curso->id }}</li>
            <li>Nombre:{{ $curso->nombre }}</li>
            <li>Duración:{{ $curso->duracion }}</li>
            <li>Fecha de Comienzo:{{ $curso->fechacomienzo }}</li>
            <li>Observaciones:{{ $curso->observaciones }}</li>
        </ul>

        <div class="botones">
            <a href={{ route('curso.edit', $curso) }} class="boton">Actualizar</a>
            <form action="{{ route('curso.destroy', $curso) }}" method="post" id="eliminar" class="form-inline">
                @csrf
                @method('delete')
                <button type="submit" class="boton">Borrar</button>
            </form>
                <button type="submit" class="boton">Eliminar otra forma</button>
           
        </div>
    </div>
@endsection